In [22]:
from TwinNeuralNetwork import TNNR, ANNR
import matplotlib.pyplot as plt

import numpy as np

In [23]:
def_func = lambda a: lambda x: x**3 - a*x

In [5]:
%%time

n = 100
seed = 9768

a = 30


tnnr_64 = TNNR(def_func(a), n=n, seed=seed, inverse_problem=True, test_pct=0.5,
               show_summary=False, show_loss_plot=False, show_rmse=False, 
               mdl_wts_file='weights/tnnr64_n' + str(n) + '_inverse_a' + str(a))

CPU times: user 3min 8s, sys: 31.9 s, total: 3min 40s
Wall time: 2min 27s


In [20]:
%%time

n = 100
seed = 9789

a = 70


tnnr_64 = ANNR(def_func(a), n=n, seed=seed, inverse_problem=True, test_pct=0.5,
               show_summary=False, show_loss_plot=False, show_rmse=False, 
               mdl_wts_file='weights/tnnr64_n' + str(n) + '_inverse_a' + str(a))

CPU times: user 33.9 s, sys: 5.04 s, total: 38.9 s
Wall time: 27 s


In [21]:
print("RMSE of TNNR 64:", tnnr_64.rmse_test)

RMSE of TNNR 64: 226.69945835299018


----------------

In [24]:
X = np.random.sample([500, 1]) * 40 - 20

In [25]:
X

array([[  6.27787359],
       [  6.59206183],
       [  3.65932771],
       [ -9.81973729],
       [ 15.26173281],
       [-12.62009904],
       [ 11.12238809],
       [  6.49833873],
       [ 19.57312568],
       [ -3.67034307],
       [ 14.49898594],
       [ -2.98611591],
       [ -9.32446323],
       [ -4.72226147],
       [  5.05479906],
       [-14.04301024],
       [-15.6657648 ],
       [ 17.0268272 ],
       [ -0.38808497],
       [-13.81387759],
       [  0.61715207],
       [ 10.82076064],
       [ -4.05095396],
       [ 18.13741301],
       [ 19.41844817],
       [-18.66456855],
       [ -1.04551421],
       [-10.2481304 ],
       [ 18.9396203 ],
       [  1.81229483],
       [ -5.47282721],
       [  3.94133047],
       [  2.03690472],
       [ 17.11249865],
       [  3.94370782],
       [  4.82403802],
       [  3.59672713],
       [ -3.31684416],
       [ 14.06507548],
       [ 12.48558726],
       [-11.52588691],
       [ -0.32124445],
       [ 19.6387927 ],
       [-19

In [26]:
from sklearn.neighbors import NearestNeighbors

In [27]:
neighborFinder = NearestNeighbors(n_neighbors=5)

In [28]:
neighborFinder.fit(X)

NearestNeighbors()

In [29]:
X_new = np.array([[3.65932771],[-9.81973729],[1.26290814],[-13.81642005]])

In [30]:
neighborFinder.kneighbors(X_new, return_distance=False)

array([[  2, 177, 373,  36, 376],
       [  3, 250,  99, 414, 340],
       [497, 134, 182, 128, 286],
       [498,  19, 157, 324, 260]])

In [31]:
np.random.permutation(len(X))

array([155, 204, 257, 399, 209,  84,  71, 187,  89, 120,  52,   9, 232,
       132, 106, 173, 356, 113,  85, 206, 437, 498, 249, 123, 492, 453,
       366, 117, 100, 110, 325, 167, 405, 485, 424, 413,  74, 298,  34,
       344, 112, 389,  40, 253, 266, 282,  37, 186, 213,  58, 239, 323,
        99, 304, 350, 421, 246, 469, 338, 322, 491, 426,  94,  14,  49,
       233, 444,  24,  83, 288, 189, 177, 196, 109, 334,  55, 124, 331,
       441, 446, 456, 450,  69,  57, 358, 318, 202, 487, 313, 170, 228,
       328, 242,  22,  62, 223,  36, 417,  51, 126, 276, 382, 340, 393,
       383, 394, 305,  97, 208, 496, 412, 427, 174, 384,  92, 489, 295,
       461, 475,  16,  48, 391, 224, 472, 346,  87, 197, 193, 231, 321,
       375, 406,  76, 300,  86, 373, 243, 347, 159, 285, 194, 388,  47,
        35, 362,   3, 317, 114, 178, 329, 454,  17, 268, 184, 108,  96,
       261,  98, 470, 102, 473, 216, 148, 274, 294, 283,  44, 445, 127,
       367, 207, 236, 245, 370,   0, 183, 315, 408, 349, 221, 43

In [49]:
s = np.array([1,2,3,4])
s

array([1, 2, 3, 4])

In [50]:
s[np.array([3,2,0,1])]  # me da el array en el orden de indices del array que es parámetro

array([4, 3, 1, 2])

In [32]:
%%time

n = 200
seed = 9876

a = 70


tnnr_test_64 = TNNR(def_func(a), n=n, seed=seed, inverse_problem=True, test_pct=0.5,
               show_summary=False, show_loss_plot=False, show_rmse=False, 
               mdl_wts_file='weights/tnnr_test_64_n' + str(n) + '_inverse_a' + str(a))

CPU times: user 1min 26s, sys: 14.8 s, total: 1min 41s
Wall time: 1min 9s


In [39]:
len(tnnr_test_64.x_train_single)

90

In [47]:
tnnr_test_64.x_train_single

array([[ 0.76435358],
       [-0.25935777],
       [ 0.84869709],
       [-0.45705006],
       [ 0.7742378 ],
       [ 0.1285967 ],
       [ 0.17598774],
       [ 0.49825854],
       [-0.18135131],
       [-0.12940732],
       [ 0.88158191],
       [-0.56432761],
       [ 0.47492748],
       [-0.14451163],
       [ 0.13166776],
       [ 0.96993889],
       [-0.7317665 ],
       [-0.58070742],
       [-0.61128265],
       [ 0.76079341],
       [ 0.22086297],
       [-0.37274693],
       [ 0.64913602],
       [ 1.        ],
       [-1.0350455 ],
       [ 0.99268655],
       [-0.92257006],
       [-0.53236284],
       [-1.04201152],
       [ 0.01498113],
       [-0.0899275 ],
       [-0.80848134],
       [-0.91242596],
       [-0.97730211],
       [-0.76318108],
       [ 0.22851209],
       [ 0.65349639],
       [-0.26145394],
       [-0.89482767],
       [-0.59068706],
       [-0.52074937],
       [-0.48849682],
       [-0.12762391],
       [ 0.74689997],
       [ 0.43905076],
       [ 0

In [102]:
tnnr_test_64.x_train_single.shape

(90, 1)

In [99]:
tnnr_test_64.y_train_single

array([ 2.27774008e+03,  2.18005947e+02,  3.32838972e+03,  7.49306161e+01,
        2.38905134e+03, -1.87654033e+02, -2.15806126e+02,  2.94982452e+02,
        1.66750043e+02,  1.12991191e+02,  3.80256642e+03, -2.46895093e+02,
        2.01404801e+02,  1.29831515e+02, -1.89960770e+02,  5.27007294e+03,
       -1.23183441e+03, -3.15324106e+02, -4.58149311e+02,  2.23838858e+03,
       -2.25420966e+02,  1.95548127e+02,  1.19315912e+03,  5.83709260e+03,
       -5.04274150e+03,  5.69586026e+03, -3.27541920e+03, -1.28821443e+02,
       -5.16757748e+03, -6.90117726e+01,  6.55574304e+01, -1.92182706e+03,
       -3.13798334e+03, -4.07831599e+03, -1.49443271e+03, -2.25148759e+02,
        1.22743771e+03,  2.18752896e+02, -2.90773536e+03, -3.59746202e+02,
       -9.07926458e+01,  1.89377636e+00,  1.10947784e+02,  2.08853420e+03,
        7.83284660e+01, -8.91459613e+01, -4.26646340e+03, -5.85961176e+03,
        2.09150833e+02, -1.90891809e+02, -8.92898801e+01,  2.23882352e+02,
        1.66258352e+02, -

In [34]:
x_data = np.array(tnnr_test_64.x_train_single)

In [36]:
perm1 = np.random.permutation(len(x_data))
perm2 = np.random.permutation(len(x_data))

In [37]:
perm1

array([87, 30, 81, 38, 56, 49, 31, 63, 55, 72, 16, 40, 62, 14, 17,  0, 71,
       26, 15, 64, 60, 84, 77, 32,  3, 13, 83, 88,  2, 59,  9, 82, 41, 61,
       20,  7, 42, 36, 57, 85, 53, 21, 48, 89, 75, 58,  4, 25, 80, 68,  6,
        5, 47, 19, 46, 22, 43, 76, 50, 54,  1, 29, 86, 79, 35, 52,  8, 18,
       70, 12, 39, 69, 37, 51, 74, 27, 34, 65, 45, 66, 78, 73, 24, 11, 10,
       33, 28, 44, 67, 23])

In [109]:
x_data[perm1]

array([[ 0.96993889],
       [ 0.7742378 ],
       [ 0.22086297],
       [-0.88595735],
       [-1.0350455 ],
       [-0.37274693],
       [ 0.46312352],
       [-0.12538877],
       [-0.52074937],
       [ 0.31869997],
       [-0.80848134],
       [-0.92257006],
       [ 0.99416225],
       [-0.7317665 ],
       [-0.12940732],
       [ 0.64913602],
       [-0.76318108],
       [ 0.68250782],
       [ 0.62364122],
       [-0.26145394],
       [-0.35400221],
       [ 0.30033455],
       [ 0.08390591],
       [ 0.85507269],
       [ 0.34609333],
       [ 1.        ],
       [ 0.39925189],
       [-0.14451163],
       [ 0.47492748],
       [ 0.49825854],
       [ 0.74689997],
       [ 0.19829494],
       [ 0.32928532],
       [ 0.84869709],
       [ 0.01498113],
       [-1.10099665],
       [ 0.1285967 ],
       [ 0.0278187 ],
       [ 0.40067948],
       [-0.18135131],
       [-0.61128265],
       [-0.49338316],
       [-0.97730211],
       [-0.48849682],
       [ 0.41103568],
       [-1

In [38]:
len(x_data)

90

In [40]:
tnnr_test_64.batch_size

16

In [42]:
batch_size_sym = tnnr_test_64.batch_size // 2
batch_size_sym

8

In [43]:
counter = 0
counter2 = 0

In [44]:
x1_batch = np.array(x_data[perm1][batch_size_sym * counter:batch_size_sym * (counter + 1)]).astype('float32')

In [45]:
x1_batch

array([[ 0.31869996],
       [-0.0899275 ],
       [ 0.6236412 ],
       [-0.89482766],
       [-0.88595736],
       [ 0.30033454],
       [-0.80848134],
       [ 0.19829494]], dtype=float32)

In [46]:
x_data[perm1]

array([[ 0.31869997],
       [-0.0899275 ],
       [ 0.62364122],
       [-0.89482767],
       [-0.88595735],
       [ 0.30033455],
       [-0.80848134],
       [ 0.19829494],
       [-0.17495463],
       [ 0.32928532],
       [-0.7317665 ],
       [-0.52074937],
       [ 0.77044768],
       [ 0.13166776],
       [-0.58070742],
       [ 0.76435358],
       [ 0.39925189],
       [-0.92257006],
       [ 0.96993889],
       [ 0.90203884],
       [ 0.34609333],
       [ 0.40067948],
       [-0.74575626],
       [-0.91242596],
       [-0.45705006],
       [-0.14451163],
       [-0.52895495],
       [ 0.927543  ],
       [ 0.84869709],
       [ 0.46069643],
       [-0.12940732],
       [ 0.0278187 ],
       [-0.48849682],
       [ 0.28247505],
       [ 0.22086297],
       [ 0.49825854],
       [-0.12762391],
       [ 0.65349639],
       [-0.07866188],
       [-0.01320097],
       [ 0.35225166],
       [-0.37274693],
       [-0.35400221],
       [-0.82379077],
       [ 0.08493255],
       [ 0

In [51]:
batch_size_sym * counter

0

In [52]:
batch_size_sym * (counter + 1)

8

In [53]:
x2_batch = np.array(x_data[perm2][batch_size_sym * counter:batch_size_sym * (counter + 1)]).astype('float32')

In [54]:
x2_batch

array([[ 0.01498113],
       [-0.12762392],
       [ 0.13166776],
       [-0.58070743],
       [ 0.19829494],
       [ 0.99416226],
       [ 0.74689996],
       [-0.07866188]], dtype=float32)

In [55]:
x_a = np.concatenate((x1_batch, x2_batch), axis=0)
x_b = np.concatenate((x2_batch, x1_batch), axis=0)

In [56]:
x_a

array([[ 0.31869996],
       [-0.0899275 ],
       [ 0.6236412 ],
       [-0.89482766],
       [-0.88595736],
       [ 0.30033454],
       [-0.80848134],
       [ 0.19829494],
       [ 0.01498113],
       [-0.12762392],
       [ 0.13166776],
       [-0.58070743],
       [ 0.19829494],
       [ 0.99416226],
       [ 0.74689996],
       [-0.07866188]], dtype=float32)

In [57]:
x_b

array([[ 0.01498113],
       [-0.12762392],
       [ 0.13166776],
       [-0.58070743],
       [ 0.19829494],
       [ 0.99416226],
       [ 0.74689996],
       [-0.07866188],
       [ 0.31869996],
       [-0.0899275 ],
       [ 0.6236412 ],
       [-0.89482766],
       [-0.88595736],
       [ 0.30033454],
       [-0.80848134],
       [ 0.19829494]], dtype=float32)

In [60]:
[x_a, x_b]

[array([[ 0.31869996],
        [-0.0899275 ],
        [ 0.6236412 ],
        [-0.89482766],
        [-0.88595736],
        [ 0.30033454],
        [-0.80848134],
        [ 0.19829494],
        [ 0.01498113],
        [-0.12762392],
        [ 0.13166776],
        [-0.58070743],
        [ 0.19829494],
        [ 0.99416226],
        [ 0.74689996],
        [-0.07866188]], dtype=float32),
 array([[ 0.01498113],
        [-0.12762392],
        [ 0.13166776],
        [-0.58070743],
        [ 0.19829494],
        [ 0.99416226],
        [ 0.74689996],
        [-0.07866188],
        [ 0.31869996],
        [-0.0899275 ],
        [ 0.6236412 ],
        [-0.89482766],
        [-0.88595736],
        [ 0.30033454],
        [-0.80848134],
        [ 0.19829494]], dtype=float32)]

In [61]:
len([x_a, x_b])

2

In [103]:
y1_batch = np.array(y_data[perm1][batch_size_sym * counter:batch_size_sym * (counter + 1)]).astype('float32')
y2_batch = np.array(y_data[perm2][batch_size_sym * counter:batch_size_sym * (counter + 1)]).astype('float32')

In [104]:
y1_batch

array([ 5270.0728 ,  2389.0513 ,  -225.42096, -2795.5586 , -5042.7417 ,
         195.54813,   158.18976,   108.37147], dtype=float32)

In [105]:
y_a = np.concatenate((y1_batch, y2_batch), axis=0)
y_b = np.concatenate((y2_batch, y1_batch), axis=0)

In [107]:
y_b

array([  -69.01177 ,   110.947784,  -189.96077 ,  -315.3241  ,
        -222.88275 ,  5724.1865  ,  2088.5342  ,    51.357197,
        5270.0728  ,  2389.0513  ,  -225.42096 , -2795.5586  ,
       -5042.7417  ,   195.54813 ,   158.18976 ,   108.37147 ],
      dtype=float32)

In [108]:
y_a - y_b

array([ 5339.0845 ,  2278.1035 ,   -35.46019, -2480.2344 , -4819.859  ,
       -5528.638  , -1930.3445 ,    57.01427, -5339.0845 , -2278.1035 ,
          35.46019,  2480.2344 ,  4819.859  ,  5528.638  ,  1930.3445 ,
         -57.01427], dtype=float32)

---------------

In [62]:
X_data = np.array(tnnr_test_64.x_train_single)
y_data = np.array(tnnr_test_64.y_train_single)

In [67]:
neighborFinder = NearestNeighbors(n_neighbors=5)

neighborFinder.fit(X_data)

nnIndicesLL = neighborFinder.kneighbors(X_data, return_distance=False)

len(nnIndicesLL) # 5 vecinos de cada data point

90

In [68]:
nnIndicesLL

array([[ 0, 19, 62,  4, 43],
       [ 1, 37, 51,  8, 55],
       [ 2, 79, 10, 64,  4],
       [ 3, 41, 69, 52, 40],
       [ 4, 62,  0, 19, 43],
       [ 5, 86, 14, 75, 67],
       [ 6, 63, 14, 20, 86],
       [ 7, 12, 70, 59, 44],
       [ 8, 55, 13,  9, 42],
       [ 9, 42, 54, 13, 30],
       [10, 64, 79,  2, 88],
       [11, 17, 39, 27, 83],
       [12, 70, 59,  7, 44],
       [13,  9, 42, 54, 55],
       [14, 86,  5,  6, 75],
       [15, 25, 68, 23, 88],
       [16, 77, 34, 31, 89],
       [17, 39, 11, 18, 27],
       [18, 39, 17, 11, 27],
       [19,  0, 62,  4, 43],
       [20, 35, 63,  6, 76],
       [21, 48, 52, 51,  3],
       [22, 36, 73, 81, 66],
       [23, 68, 25, 15, 88],
       [24, 28, 47, 46, 33],
       [25, 68, 23, 15, 88],
       [26, 80, 32, 38, 56],
       [27, 83, 40, 11, 69],
       [28, 24, 47, 46, 65],
       [29, 82, 45, 50, 78],
       [30, 57, 54, 42,  9],
       [31, 89, 34, 77, 16],
       [32, 80, 26, 38, 56],
       [33, 46, 26, 24, 80],
       [34, 77

In [69]:
[np.random.shuffle(x) for x in nnIndicesLL]  # shuffle las listas y su contenido también

nnIndicesLL

array([[62,  4, 43, 19,  0],
       [55,  8,  1, 37, 51],
       [ 4, 79,  2, 64, 10],
       [ 3, 41, 52, 40, 69],
       [ 4,  0, 19, 62, 43],
       [67, 75, 14, 86,  5],
       [63, 20,  6, 86, 14],
       [70, 44, 12,  7, 59],
       [42, 55,  8,  9, 13],
       [13,  9, 54, 30, 42],
       [ 2, 64, 79, 88, 10],
       [83, 17, 27, 11, 39],
       [ 7, 59, 12, 44, 70],
       [13, 54, 55,  9, 42],
       [86,  6, 14,  5, 75],
       [15, 88, 25, 68, 23],
       [77, 34, 16, 31, 89],
       [27, 18, 11, 17, 39],
       [11, 17, 39, 18, 27],
       [19, 43,  0, 62,  4],
       [76,  6, 35, 63, 20],
       [21, 51, 52, 48,  3],
       [36, 22, 81, 73, 66],
       [68, 15, 23, 88, 25],
       [33, 24, 47, 28, 46],
       [25, 15, 68, 23, 88],
       [26, 32, 80, 56, 38],
       [69, 11, 27, 83, 40],
       [28, 65, 47, 24, 46],
       [82, 45, 29, 78, 50],
       [57,  9, 42, 30, 54],
       [34, 31, 77, 16, 89],
       [32, 26, 38, 56, 80],
       [24, 46, 26, 80, 33],
       [31, 77

In [71]:
batch_size = tnnr_test_64.batch_size//2
batch_size

8

In [72]:
num_single_samples = X_data.shape[0]

num_single_samples

90

In [73]:
batches_per_sweep = num_single_samples/batch_size
batches_per_sweep

11.25

In [74]:
counter = 0
    
perm1 = np.random.permutation(len(X_data))

In [75]:
neighbor_num = 5

i1, i2 = np.random.choice(range(neighbor_num), 2, replace=False)

print(i1)
print(i2)

0
3


In [76]:
X1 = X_data[perm1]
X2 = X_data[nnIndicesLL[perm1][:, i1]] # estos son los vecinos (todos en la posición i1)
X3 = X_data[nnIndicesLL[perm1][:, i2]]

In [78]:
perm1

array([15,  4, 20, 56, 24, 21, 70, 54, 40, 87, 31, 26, 68, 16,  9, 22, 34,
       66, 81, 37, 48, 49, 67, 79, 60, 23, 71, 13, 12,  7, 43, 63, 72,  2,
       29, 65,  5, 82, 84,  8, 18, 69, 33, 41, 58, 28,  0, 88, 39,  1, 89,
       73, 45, 27, 55, 75, 44, 36,  3, 52,  6, 76, 19, 85, 14, 61, 51, 78,
       35, 42, 62, 80, 53, 83, 38, 30, 77, 46, 50, 74, 11, 64, 86, 57, 10,
       32, 47, 25, 17, 59])

In [79]:
len(X1)

90

In [82]:
X1[: 10] # los 10 primeros elementos, X1 tienen lo de X_data pero en un nuevoorden dado por perm1 (que son indices)

array([[ 0.96993889],
       [ 0.7742378 ],
       [ 0.22086297],
       [-0.88595735],
       [-1.0350455 ],
       [-0.37274693],
       [ 0.46312352],
       [-0.12538877],
       [-0.52074937],
       [ 0.31869997]])

In [84]:
len(X2)

90

In [88]:
len(X3)

90

In [85]:
nnIndicesLL[perm1] # los indices en el orden de perm1 (pa que?)

array([[15, 88, 25, 68, 23],
       [ 4,  0, 19, 62, 43],
       [76,  6, 35, 63, 20],
       [32, 56, 80, 26, 38],
       [33, 24, 47, 28, 46],
       [21, 51, 52, 48,  3],
       [59,  7, 12, 44, 70],
       [13, 42,  9, 54, 30],
       [27, 83, 69, 40, 41],
       [87, 74, 60, 49, 72],
       [34, 31, 77, 16, 89],
       [26, 32, 80, 56, 38],
       [68, 15, 23, 88, 25],
       [77, 34, 16, 31, 89],
       [13,  9, 54, 30, 42],
       [36, 22, 81, 73, 66],
       [31, 77, 16, 34, 89],
       [66, 81, 22, 73, 36],
       [66, 36, 81, 73, 22],
       [55,  8, 51,  1, 37],
       [51, 48, 52, 21, 37],
       [61, 76, 74, 49, 87],
       [ 5, 67, 75, 86, 78],
       [ 2, 10, 88, 64, 79],
       [53, 60, 72, 74, 87],
       [68, 15, 23, 88, 25],
       [44, 53, 58, 84, 71],
       [13, 54, 55,  9, 42],
       [ 7, 59, 12, 44, 70],
       [70, 44, 12,  7, 59],
       [ 4,  0, 43, 19, 62],
       [20,  6, 63, 35, 14],
       [74, 87, 60, 53, 72],
       [ 4, 79,  2, 64, 10],
       [82, 45

In [86]:
nnIndicesLL[perm1][:, i1] # todos los indices en la posicion i1 = 0

array([15,  4, 76, 32, 33, 21, 59, 13, 27, 87, 34, 26, 68, 77, 13, 36, 31,
       66, 66, 55, 51, 61,  5,  2, 53, 68, 44, 13,  7, 70,  4, 20, 74,  4,
       82, 65, 67, 78, 53, 42, 11, 69, 24, 40, 71, 28, 62, 88, 27, 55, 34,
       73, 29, 69,  8, 86, 12, 73,  3, 52, 63, 49, 19, 29, 86, 61, 48, 29,
       63, 54, 19, 56, 72, 11, 32, 57, 31, 46, 45, 87, 83, 64, 75, 42,  2,
       32, 24, 25, 27, 12])

In [87]:
nnIndicesLL[perm1][:, i2] # todos los indices en la posicion i2 = 3

array([68, 62, 63, 26, 28, 48, 44, 54, 40, 49, 16, 56, 88, 31, 30, 73, 34,
       73, 73,  1, 21, 49, 86, 64, 74, 88, 84,  9, 44,  7, 19, 35, 53, 64,
       78, 46, 86, 82, 58,  9, 18, 41, 80, 69, 58, 24, 19, 25, 17, 37, 31,
       66, 78, 83,  9, 78, 70, 81, 40, 48, 86, 76, 62, 82,  5, 76, 37, 50,
       76, 42, 43, 80, 74, 40, 56, 30, 77, 28, 29, 74, 11, 79,  5,  9, 88,
       56, 47, 23, 17,  7])

In [110]:
X3

array([[ 0.99416225],
       [ 0.77044768],
       [ 0.19829494],
       [-0.92257006],
       [-1.04201152],
       [-0.35400221],
       [ 0.43905076],
       [-0.12538877],
       [-0.52074937],
       [ 0.30033455],
       [-0.7317665 ],
       [-0.88595735],
       [ 0.927543  ],
       [-0.80848134],
       [-0.0899275 ],
       [ 0.62394559],
       [-0.76318108],
       [ 0.62394559],
       [ 0.62394559],
       [-0.25935777],
       [-0.37274693],
       [ 0.30033455],
       [ 0.1291474 ],
       [ 0.90203884],
       [ 0.32756634],
       [ 0.927543  ],
       [ 0.40067948],
       [-0.12940732],
       [ 0.43905076],
       [ 0.49825854],
       [ 0.76079341],
       [ 0.22851209],
       [ 0.35225166],
       [ 0.90203884],
       [ 0.04200883],
       [-0.98917006],
       [ 0.1291474 ],
       [ 0.0278187 ],
       [ 0.41103568],
       [-0.12940732],
       [-0.61128265],
       [-0.48849682],
       [-0.91676892],
       [-0.49338316],
       [ 0.41103568],
       [-1

In [89]:
# lo mismo con y
y1 = y_data[perm1]
y2 = y_data[nnIndicesLL[perm1][:, i1]]
y3 = y_data[nnIndicesLL[perm1][:, i2]]

In [90]:
len(y3)

90

In [91]:
X1_batch = np.array(X1[batch_size*counter:batch_size*(counter+1)]).astype('float32')
X2_batch = np.array(X2[batch_size*counter:batch_size*(counter+1)]).astype('float32')
X3_batch = np.array(X3[batch_size*counter:batch_size*(counter+1)]).astype('float32')        
        
y1_batch = np.array(y1[batch_size*counter:batch_size*(counter+1)]).astype('float32')
y2_batch = np.array(y2[batch_size*counter:batch_size*(counter+1)]).astype('float32')
y3_batch = np.array(y3[batch_size*counter:batch_size*(counter+1)]).astype('float32')

In [92]:
X1_batch

array([[ 0.9699389 ],
       [ 0.7742378 ],
       [ 0.22086297],
       [-0.88595736],
       [-1.0350455 ],
       [-0.3727469 ],
       [ 0.46312353],
       [-0.12538877]], dtype=float32)

In [93]:
X_A = np.concatenate((X1_batch, X2_batch), axis=0)

In [94]:
X_A

array([[ 0.9699389 ],
       [ 0.7742378 ],
       [ 0.22086297],
       [-0.88595736],
       [-1.0350455 ],
       [-0.3727469 ],
       [ 0.46312353],
       [-0.12538877],
       [ 0.9699389 ],
       [ 0.7742378 ],
       [ 0.27233258],
       [-0.91242594],
       [-0.97730213],
       [-0.3727469 ],
       [ 0.46069643],
       [-0.14451163]], dtype=float32)

In [95]:
X_B = np.concatenate((X2_batch, X1_batch), axis=0)
X_B

array([[ 0.9699389 ],
       [ 0.7742378 ],
       [ 0.27233258],
       [-0.91242594],
       [-0.97730213],
       [-0.3727469 ],
       [ 0.46069643],
       [-0.14451163],
       [ 0.9699389 ],
       [ 0.7742378 ],
       [ 0.22086297],
       [-0.88595736],
       [-1.0350455 ],
       [-0.3727469 ],
       [ 0.46312353],
       [-0.12538877]], dtype=float32)

In [96]:
[X_A, X_B]

[array([[ 0.9699389 ],
        [ 0.7742378 ],
        [ 0.22086297],
        [-0.88595736],
        [-1.0350455 ],
        [-0.3727469 ],
        [ 0.46312353],
        [-0.12538877],
        [ 0.9699389 ],
        [ 0.7742378 ],
        [ 0.27233258],
        [-0.91242594],
        [-0.97730213],
        [-0.3727469 ],
        [ 0.46069643],
        [-0.14451163]], dtype=float32),
 array([[ 0.9699389 ],
        [ 0.7742378 ],
        [ 0.27233258],
        [-0.91242594],
        [-0.97730213],
        [-0.3727469 ],
        [ 0.46069643],
        [-0.14451163],
        [ 0.9699389 ],
        [ 0.7742378 ],
        [ 0.22086297],
        [-0.88595736],
        [-1.0350455 ],
        [-0.3727469 ],
        [ 0.46312353],
        [-0.12538877]], dtype=float32)]

In [97]:
y_a = np.concatenate((y1_batch, y2_batch), axis=0)
y_b = np.concatenate((y2_batch, y1_batch), axis=0)

In [98]:
y_a - y_b

array([   0.      ,    0.      ,  -13.953201,  342.4248  , -964.4258  ,
          0.      ,    8.550171,  -21.460045,    0.      ,    0.      ,
         13.953201, -342.4248  ,  964.4258  ,    0.      ,   -8.550171,
         21.460045], dtype=float32)

---------

In [116]:
x_data = np.array(tnnr_test_64.x_train_single)
y_data = np.array(tnnr_test_64.y_train_single)

In [120]:
x_data

array([[ 0.76435358],
       [-0.25935777],
       [ 0.84869709],
       [-0.45705006],
       [ 0.7742378 ],
       [ 0.1285967 ],
       [ 0.17598774],
       [ 0.49825854],
       [-0.18135131],
       [-0.12940732],
       [ 0.88158191],
       [-0.56432761],
       [ 0.47492748],
       [-0.14451163],
       [ 0.13166776],
       [ 0.96993889],
       [-0.7317665 ],
       [-0.58070742],
       [-0.61128265],
       [ 0.76079341],
       [ 0.22086297],
       [-0.37274693],
       [ 0.64913602],
       [ 1.        ],
       [-1.0350455 ],
       [ 0.99268655],
       [-0.92257006],
       [-0.53236284],
       [-1.04201152],
       [ 0.01498113],
       [-0.0899275 ],
       [-0.80848134],
       [-0.91242596],
       [-0.97730211],
       [-0.76318108],
       [ 0.22851209],
       [ 0.65349639],
       [-0.26145394],
       [-0.89482767],
       [-0.59068706],
       [-0.52074937],
       [-0.48849682],
       [-0.12762391],
       [ 0.74689997],
       [ 0.43905076],
       [ 0

In [122]:
neighbor_finder = NearestNeighbors(n_neighbors=5)
neighbor_finder.fit(x_data)
nn_indexes = neighbor_finder.kneighbors(x_data, return_distance=False)
nn_indexes

array([[ 0, 19, 62,  4, 43],
       [ 1, 37, 51,  8, 55],
       [ 2, 79, 10, 64,  4],
       [ 3, 41, 69, 52, 40],
       [ 4, 62,  0, 19, 43],
       [ 5, 86, 14, 75, 67],
       [ 6, 63, 14, 20, 86],
       [ 7, 12, 70, 59, 44],
       [ 8, 55, 13,  9, 42],
       [ 9, 42, 54, 13, 30],
       [10, 64, 79,  2, 88],
       [11, 17, 39, 27, 83],
       [12, 70, 59,  7, 44],
       [13,  9, 42, 54, 55],
       [14, 86,  5,  6, 75],
       [15, 25, 68, 23, 88],
       [16, 77, 34, 31, 89],
       [17, 39, 11, 18, 27],
       [18, 39, 17, 11, 27],
       [19,  0, 62,  4, 43],
       [20, 35, 63,  6, 76],
       [21, 48, 52, 51,  3],
       [22, 36, 73, 81, 66],
       [23, 68, 25, 15, 88],
       [24, 28, 47, 46, 33],
       [25, 68, 23, 15, 88],
       [26, 80, 32, 38, 56],
       [27, 83, 40, 11, 69],
       [28, 24, 47, 46, 65],
       [29, 82, 45, 50, 78],
       [30, 57, 54, 42,  9],
       [31, 89, 34, 77, 16],
       [32, 80, 26, 38, 56],
       [33, 46, 26, 24, 80],
       [34, 77

In [124]:
[np.random.shuffle(x) for x in nn_indexes]
nn_indexes

array([[ 4, 43,  0, 62, 19],
       [ 1, 51, 37, 55,  8],
       [ 2, 64, 10, 79,  4],
       [41, 52, 40,  3, 69],
       [43, 62, 19,  4,  0],
       [14, 86, 67, 75,  5],
       [63, 86, 14,  6, 20],
       [44, 70, 59,  7, 12],
       [ 8, 55, 13,  9, 42],
       [30, 42,  9, 54, 13],
       [10,  2, 88, 64, 79],
       [11, 39, 17, 27, 83],
       [70, 59, 44,  7, 12],
       [ 9, 54, 42, 55, 13],
       [14, 86,  6, 75,  5],
       [25, 15, 88, 23, 68],
       [89, 77, 31, 34, 16],
       [27, 17, 39, 18, 11],
       [27, 39, 11, 17, 18],
       [43, 19,  4,  0, 62],
       [76, 20, 35, 63,  6],
       [51, 48,  3, 21, 52],
       [22, 66, 81, 73, 36],
       [68, 25, 88, 23, 15],
       [47, 28, 24, 33, 46],
       [25, 68, 15, 23, 88],
       [80, 56, 38, 26, 32],
       [69, 27, 11, 40, 83],
       [46, 47, 65, 24, 28],
       [50, 78, 82, 29, 45],
       [54,  9, 42, 30, 57],
       [34, 77, 31, 16, 89],
       [80, 26, 38, 32, 56],
       [46, 24, 80, 26, 33],
       [31, 34

In [125]:
batch_size_sym = 8

In [126]:
num_single_samples = x_data.shape[0]
batches_per_sweep = num_single_samples / batch_size_sym
counter = 0

In [127]:
num_single_samples

90

In [128]:
batches_per_sweep

11.25

In [129]:
perm1 = np.random.permutation(len(x_data))
perm1

array([88, 38, 27, 14, 75, 55, 23, 80, 20, 29, 24, 54, 30, 85,  3, 12, 69,
       51, 70, 56, 40, 53, 41, 37, 86,  0, 15, 22, 19, 35, 48, 84, 18, 74,
       17, 72, 71, 25,  1, 39, 26, 46, 78, 47, 60, 64, 67,  5, 76, 10, 49,
       87, 34, 52,  9, 44, 50, 81, 83, 16, 61, 79, 73, 68, 43, 77, 32,  6,
       65, 63, 66, 62, 58, 42, 33, 11,  7, 21,  2, 59, 82,  4, 36,  8, 45,
       31, 57, 89, 13, 28])

In [132]:
i1 = np.random.choice(range(5), 1, replace=False)

In [133]:
i1

array([1])

In [134]:
x1 = x_data[perm1]
x1

array([[ 0.927543  ],
       [-0.89482767],
       [-0.53236284],
       [ 0.13166776],
       [ 0.08493255],
       [-0.17495463],
       [ 1.        ],
       [-0.91676892],
       [ 0.22086297],
       [ 0.01498113],
       [-1.0350455 ],
       [-0.12538877],
       [-0.0899275 ],
       [-0.01320097],
       [-0.45705006],
       [ 0.47492748],
       [-0.49338316],
       [-0.31622906],
       [ 0.46312352],
       [-0.88595735],
       [-0.52074937],
       [ 0.35225166],
       [-0.48849682],
       [-0.26145394],
       [ 0.1291474 ],
       [ 0.76435358],
       [ 0.96993889],
       [ 0.64913602],
       [ 0.76079341],
       [ 0.22851209],
       [-0.35400221],
       [ 0.40067948],
       [-0.61128265],
       [ 0.32756634],
       [-0.58070742],
       [ 0.32928532],
       [ 0.39925189],
       [ 0.99268655],
       [-0.25935777],
       [-0.59068706],
       [-0.92257006],
       [-0.98917006],
       [ 0.04200883],
       [-1.07887145],
       [ 0.34609333],
       [ 0

In [135]:
x2 = x_data[nn_indexes[perm1][:, i1]]
x2

array([[[ 0.99268655]],

       [[-0.91676892]],

       [[-0.53236284]],

       [[ 0.1291474 ]],

       [[ 0.08493255]],

       [[-0.12762391]],

       [[ 0.99268655]],

       [[-0.91242596]],

       [[ 0.22086297]],

       [[ 0.04200883]],

       [[-1.04201152]],

       [[-0.12762391]],

       [[-0.12940732]],

       [[-0.01320097]],

       [[-0.40114623]],

       [[ 0.46069643]],

       [[-0.52074937]],

       [[-0.37274693]],

       [[ 0.46312352]],

       [[-0.92257006]],

       [[-0.48849682]],

       [[ 0.32756634]],

       [[-0.45705006]],

       [[-0.25935777]],

       [[ 0.08390591]],

       [[ 0.74689997]],

       [[ 0.96993889]],

       [[ 0.68250782]],

       [[ 0.76079341]],

       [[ 0.19829494]],

       [[-0.31622906]],

       [[ 0.43905076]],

       [[-0.59068706]],

       [[ 0.34609333]],

       [[-0.58070742]],

       [[ 0.35225166]],

       [[ 0.40067948]],

       [[ 0.99416225]],

       [[-0.31622906]],

       [[-0.59068706]],



In [140]:
np.array([[x[0][0]] for x in x2])

array([[ 0.99268655],
       [-0.91676892],
       [-0.53236284],
       [ 0.1291474 ],
       [ 0.08493255],
       [-0.12762391],
       [ 0.99268655],
       [-0.91242596],
       [ 0.22086297],
       [ 0.04200883],
       [-1.04201152],
       [-0.12762391],
       [-0.12940732],
       [-0.01320097],
       [-0.40114623],
       [ 0.46069643],
       [-0.52074937],
       [-0.37274693],
       [ 0.46312352],
       [-0.92257006],
       [-0.48849682],
       [ 0.32756634],
       [-0.45705006],
       [-0.25935777],
       [ 0.08390591],
       [ 0.74689997],
       [ 0.96993889],
       [ 0.68250782],
       [ 0.76079341],
       [ 0.19829494],
       [-0.31622906],
       [ 0.43905076],
       [-0.59068706],
       [ 0.34609333],
       [-0.58070742],
       [ 0.35225166],
       [ 0.40067948],
       [ 0.99416225],
       [-0.31622906],
       [-0.59068706],
       [-0.88595735],
       [-0.92257006],
       [ 0.01498113],
       [-1.0350455 ],
       [ 0.32756634],
       [ 0

In [144]:
nn_indexes[perm1][:, 1]

array([25, 80, 27, 86, 75, 42, 25, 32, 20, 78, 28, 42,  9, 85, 52, 59, 40,
       21, 70, 26, 41, 74,  3,  1, 67, 43, 15, 66, 19, 63, 51, 44, 39, 60,
       17, 53, 84, 68, 51, 39, 56, 26, 29, 24, 74,  2, 86, 86, 87,  2, 87,
       74, 34,  3, 42, 58, 45, 81, 11, 77, 74, 79, 66, 25,  4, 89, 26, 86,
       65, 35, 36,  0, 84, 54, 24, 39, 70, 48, 64, 59, 78, 62, 81, 55, 29,
       77, 30, 38, 54, 47])

In [146]:
x_data[nn_indexes[perm1][:, 1  ]]

array([[ 0.99268655],
       [-0.91676892],
       [-0.53236284],
       [ 0.1291474 ],
       [ 0.08493255],
       [-0.12762391],
       [ 0.99268655],
       [-0.91242596],
       [ 0.22086297],
       [ 0.04200883],
       [-1.04201152],
       [-0.12762391],
       [-0.12940732],
       [-0.01320097],
       [-0.40114623],
       [ 0.46069643],
       [-0.52074937],
       [-0.37274693],
       [ 0.46312352],
       [-0.92257006],
       [-0.48849682],
       [ 0.32756634],
       [-0.45705006],
       [-0.25935777],
       [ 0.08390591],
       [ 0.74689997],
       [ 0.96993889],
       [ 0.68250782],
       [ 0.76079341],
       [ 0.19829494],
       [-0.31622906],
       [ 0.43905076],
       [-0.59068706],
       [ 0.34609333],
       [-0.58070742],
       [ 0.35225166],
       [ 0.40067948],
       [ 0.99416225],
       [-0.31622906],
       [-0.59068706],
       [-0.88595735],
       [-0.92257006],
       [ 0.01498113],
       [-1.0350455 ],
       [ 0.32756634],
       [ 0

In [150]:
x_data[nn_indexes[perm1][:, i1[0]]]

array([[ 0.99268655],
       [-0.91676892],
       [-0.53236284],
       [ 0.1291474 ],
       [ 0.08493255],
       [-0.12762391],
       [ 0.99268655],
       [-0.91242596],
       [ 0.22086297],
       [ 0.04200883],
       [-1.04201152],
       [-0.12762391],
       [-0.12940732],
       [-0.01320097],
       [-0.40114623],
       [ 0.46069643],
       [-0.52074937],
       [-0.37274693],
       [ 0.46312352],
       [-0.92257006],
       [-0.48849682],
       [ 0.32756634],
       [-0.45705006],
       [-0.25935777],
       [ 0.08390591],
       [ 0.74689997],
       [ 0.96993889],
       [ 0.68250782],
       [ 0.76079341],
       [ 0.19829494],
       [-0.31622906],
       [ 0.43905076],
       [-0.59068706],
       [ 0.34609333],
       [-0.58070742],
       [ 0.35225166],
       [ 0.40067948],
       [ 0.99416225],
       [-0.31622906],
       [-0.59068706],
       [-0.88595735],
       [-0.92257006],
       [ 0.01498113],
       [-1.0350455 ],
       [ 0.32756634],
       [ 0

In [152]:
a, = np.random.choice(range(5), 1, replace=False)

In [153]:
a

3

In [154]:
[3] * 5

[3, 3, 3, 3, 3]